# Generated by Django 5.1.7 on 2025-04-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PHONE', 'Smartphone'), ('CAMERA', 'Camera'), ('WATCH', 'Smartwatch'), ('HEADPHONE', 'Headphone'), ('COMPUTER', 'Computer'), ('GAMING', 'Gaming')], max_length=20),
        ),
    ]
